/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * featureOptions-docs.ts: Pure, isomorphic renderer that projects a feature-options catalog into the markdown reference each plugin ships in its docs.
 */

/**
 * A shared documentation renderer for the {@link featureOptions!FeatureOptions | FeatureOptions} catalog.
 *
 * Every plugin's feature-options catalog needs a markdown category index plus per-category option tables rendered into its `docs/FeatureOptions.md`. This module
 * renders that projection once, so every plugin shares one implementation of the dotted-key construction and the value-vs-toggle distinction that this library
 * already owns as single-source-of-truth helpers, and the documentation stays a pure projection of the live catalog.
 *
 * The module exports one pure string function:
 *
 *   - {@link renderFeatureOptionsReference} - the projection itself. It derives every key via {@link expandOption}, decides value-ness via {@link isValueOption}, and
 *     builds the catalog index once via {@link buildCatalogIndex}; it never re-derives any of those. Plugin-private scope prose is supplied through two optional render
 *     hooks that mirror the webUI's field-blind `validOption` / `validOptionCategory` predicate boundary, lifted from *filter* (boolean) to *describe* (string). No
 *     plugin-specific field name appears anywhere in this file.
 *
 * Putting the rendered fragment into a plugin's doc is {@link doc-markdown!spliceMarkedRegion}, the in-place splice every generator's CLI verb uses, and the table
 * layout the projection prints its option rows through is {@link doc-markdown!renderMarkdownTable}.
 *
 * It also ships two builders for those scope hooks, because writing them by hand is what every plugin was doing and the results converged on two shapes. Neither builder
 * is required - a plugin with prose of its own still writes the hooks directly - but between them they cover what the family actually says.
 * {@link buildFixedScopeDescribers} produces the fixed pair of sentences a plugin with a flat global-or-per-device hierarchy wants;
 * {@link buildComposedScopeDescribers} composes a sentence from a plugin's own vocabulary for the levels it names, for a hierarchy the fixed sentences cannot describe.
 *
 * The renderer is pure and isomorphic: no `node:` imports, no `fs`, no `process`. The only I/O - reading the doc and writing it back - is two lines of
 * `node:fs/promises` in each plugin's build-script shim, which is inherently a tooling concern. This module is therefore browser-safe and trivially testable, but it
 * is a tooling concern and is deliberately NOT mirrored into `dist/ui/` by the build pipeline.
 *
 * @module
 */
import { ALL_CHOICES, buildCatalogIndex, expandOption, isValueOption } from "./featureOptions.ts";
import type { FeatureCategoryEntry, FeatureOptionEntry, FeatureOptionScope } from "./featureOptions.ts";
import { renderMarkdownTable } from "./doc-markdown.ts";

/**
 * The opening marker of the auto-generated region in a plugin's `docs/FeatureOptions.md`. The documentation module's {@link doc-markdown!spliceMarkedRegion} replaces
 * everything strictly between this marker and {@link FEATURE_OPTIONS_DOC_END}, preserving both markers and the hand-written prose around them. The text doubles as an
 * in-document warning to maintainers not to edit the region by hand.
 *
 * @category Feature Options
 */
export const FEATURE_OPTIONS_DOC_BEGIN = "<!-- FEATURE OPTIONS:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated region. See {@link FEATURE_OPTIONS_DOC_BEGIN}.
 *
 * @category Feature Options
 */
export const FEATURE_OPTIONS_DOC_END = "<!-- FEATURE OPTIONS:END -->";

// The fixed width, in dashes, of the description-side divider segment {@link doc-markdown!renderMarkdownTable} draws for this document. The Option-side width is
// auto-computed per table from the visible cell widths; the description side has no upper bound worth chasing (descriptions plus scope suffixes can be arbitrarily
// long), so it is a sensible constant rather than a second max pass. Padding is cosmetic - rendered markdown ignores it - so this is presentation polish, not part of
// the semantic contract.
const DESCRIPTION_DIVIDER_WIDTH = 61;

// The substitution shown in the default cell for a value option whose declared default is the empty string. We render "none" rather than an empty cell so the table
// communicates "this option defaults to no value" explicitly. The substitution happens at render time only; the catalog entry is never mutated.
const EMPTY_DEFAULT_LABEL = "none";

// The substitution shown in the default cell for a multi-select whose declared default is the all-choices spelling. That default stands for every member of a
// domain the catalog cannot enumerate, so the table reads it out as the word it means rather than printing a character a reader would have to go look up.
const ALL_CHOICES_LABEL = "all";

// Render a value option's declared default as the table shows it. Two catalog spellings stand for something other than themselves and are read out as words: the
// empty default, which says the option starts with no value, and a multi-select's all-choices default, which says every member of its domain is selected. Every
// other default prints as the text a user would type into their configuration. The substitution happens at render time only; the catalog entry is never mutated.
function renderDefaultValue(option: FeatureOptionEntry): string {

  if(option.multiple && (option.defaultValue === ALL_CHOICES)) {

    return ALL_CHOICES_LABEL;
  }

  return ((option.defaultValue ?? "") === "") ? EMPTY_DEFAULT_LABEL : escapeCellText(String(option.defaultValue));
}

// Escape catalog-derived plain text for safe embedding in a markdown table cell, heading, or index line. We neutralize the column separator "|" (which would inject
// a phantom table column) and the HTML-significant "&", "<", ">" (which would otherwise be parsed as markup and swallowed). "&" is replaced first so the entities we
// introduce are not themselves re-escaped. This is applied ONLY to catalog-derived plain text (descriptions and the rendered default value); it is deliberately NOT
// applied to the dotted key (a constrained identifier that also lives inside a code span where entities would not decode), to the renderer's own structural HTML
// (the per-row/heading anchors) or the "=<value>" placeholder, nor to the scope-hook return values (the plugin owns that markup - e.g. a "<BR>" line break).
function escapeCellText(text: string): string {

  return text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("|", "\\|");
}

/**
 * Render a feature-options catalog into the markdown reference fragment a plugin embeds in its `docs/FeatureOptions.md`. The output is a category index (one bullet per
 * category, deep-linking to its detail section), an optional one-line legend explaining the `=<value>` notation, and then one detail section per category, each carrying
 * an optional device-scope line and a flat table of option rows. The legend is emitted only when the catalog has at least one value option, since a toggle-only catalog
 * never renders the `=<value>` placeholder the legend describes.
 *
 * The renderer owns all base-shaped scaffolding - the index, headings, per-row deep-link anchors, the key cell with its value/toggle placeholder, the default cell, the
 * description cell, and the column math - purely from the base {@link FeatureOptionEntry} / {@link FeatureCategoryEntry} fields. The two optional hooks own *only* the
 * plugin-private scope prose: `describeCategoryScope` contributes the device-scope sentence under a category heading, and `describeOptionScope` contributes a suffix
 * appended to an option's description cell. A hook returning `undefined` omits its contribution cleanly - never an "undefined" literal, never a stray blank line.
 *
 * The catalog index is built once via {@link buildCatalogIndex}; value-ness is decided via {@link isValueOption}; the canonical dotted key is derived via
 * {@link expandOption}. None of those is re-derived here - the renderer is a projection of the same single source of truth the rest of the module owns.
 *
 * @typeParam TOptionMeta   - The concrete type of an option entry's opaque `meta` annotation, reconstituted at this boundary so `describeOptionScope` sees it typed.
 * @typeParam TCategoryMeta - The concrete type of a category entry's opaque `meta` annotation, reconstituted so `describeCategoryScope` sees it typed.
 * @param input
 * @param input.categories            - The catalog's category list, in the order the index and detail sections should follow.
 * @param input.describeCategoryScope - Optional. Returns the device-scope sentence emitted under a category's heading, or `undefined` to omit it. The hook owns the full
 *                                      sentence including any leading or trailing text.
 * @param input.describeOptionScope   - Optional. Returns a suffix appended to an option's description cell, or `undefined` to omit it. The hook owns its full text
 *                                      including any leading separator.
 * @param input.options               - The catalog's options map keyed by category name.
 *
 * @returns The rendered markdown fragment.
 */
export function renderFeatureOptionsReference<TOptionMeta = unknown, TCategoryMeta = unknown>(input: {
  categories: readonly FeatureCategoryEntry<TCategoryMeta>[];
  describeCategoryScope?: (category: FeatureCategoryEntry<TCategoryMeta>) => string | undefined;
  describeOptionScope?: (option: FeatureOptionEntry<TOptionMeta>, category: FeatureCategoryEntry<TCategoryMeta>) => string | undefined;
  options: Readonly<Record<string, readonly FeatureOptionEntry<TOptionMeta>[]>>;
}): string {

  const { categories, describeCategoryScope, describeOptionScope, options } = input;

  // Build the catalog index once. We never re-derive value-options, defaults, or the dotted key downstream - everything routes back through this single source of
  // truth. The index accepts the typed arrays because a parameterized entry is structurally assignable to the base entry the index is declared over.
  const catalog = buildCatalogIndex(categories, options);

  // Accumulate the rendered lines. We assemble line-by-line and join with newlines at the end rather than concatenating strings, which keeps the blank-line discipline
  // explicit (a pushed empty string is a blank line) and avoids a forest of "\n" literals.
  const lines: string[] = [];

  // Index pass: one bullet per category, deep-linking to the category's detail heading. We iterate the typed `categories` array directly - not `catalog.categories`,
  // which is base-typed - and apply the same "skip a category with no options entry" rule the index builder uses, so the two traversals cannot disagree. The bullet's
  // link text is the category name; the anchor is its lowercased form; the trailing text is the category description verbatim, with no appended suffix.
  for(const category of categories) {

    if(!options[category.name]) {

      continue;
    }

    lines.push(" * [" + category.name + "](#" + category.name.toLowerCase() + "): " + escapeCellText(category.description));
  }

  // A single blank line separates the index from the detail sections.
  lines.push("");

  // Conditional legend. When the catalog has at least one value option, we explain the renderer's own "=<value>" notation - the suffix it appends to value-option keys -
  // so a reader knows to substitute their setting rather than typing the literal placeholder, and that every other option is a simple on/off toggle. The legend is
  // suppressed for a toggle-only catalog (no value options) where the "=<value>" notation never appears, so the explanation would document a notation the reader never
  // sees. It sits after the index's trailing blank line and is itself followed by a blank line, keeping it cleanly framed before the first detail heading.
  if(catalog.sortedValueOptionNames.length > 0) {

    lines.push("Options whose key ends in `=<value>` take a value - replace `=<value>` with your setting; all other options are simple on/off toggles. " +
      "The default shown for each option is what applies when you leave it unset.");
    lines.push("");
  }

  // Detail pass: one section per category, in catalog order.
  for(const category of categories) {

    const categoryOptions = options[category.name];

    // Skip a category with no options entry, matching the index builder's rule so the detail traversal stays in lockstep with the index.
    if(!categoryOptions) {

      continue;
    }

    // Heading with an invisible anchor so the index bullets can deep-link to it. The visible text is the category description, verbatim.
    lines.push("#### <A NAME=\"" + category.name.toLowerCase() + "\"></A>" + escapeCellText(category.description));
    lines.push("");

    // Optional device-scope line. The hook owns the full sentence; when it returns `undefined` we omit the line and its trailing blank line entirely rather than
    // emitting an empty row or the literal string "undefined".
    const categoryScope = describeCategoryScope?.(category);

    if(categoryScope !== undefined) {

      lines.push(categoryScope);
      lines.push("");
    }

    // Compose each option's two cells - the key cell and the description cell - up front so we can size the Option column to the widest visible key cell before we
    // emit any table line. This is the single max pass the column math needs; nothing downstream re-walks the options.
    const rows = categoryOptions.map((option) => {

      // The canonical dotted key (single source of truth - never hand-concatenated). For a category-level option (empty name), `expandOption` returns the category
      // name alone, which is exactly the bare-category key we want to render.
      const key = expandOption(category, option);

      // The key cell pairs an invisible per-row anchor (key case preserved, so deep links are stable) with a single backtick code span. Value-ness is signaled
      // lexically by appending the universal "=<value>" placeholder inside the same span - no mixed HTML, faithful to the template the user fills in.
      const keyCell = "<A NAME=\"" + key + "\"></A>`" + key + (isValueOption(catalog, key) ? "=<value>" : "") + "`";

      // The default cell. A value option shows its declared default in the form the user would type - never formatted, since a formatted value (e.g. "30s") is an
      // invalid config value - through the one renderer that also words the two spellings standing for something else. A toggle shows enabled / disabled.
      const defaultCell = isValueOption(catalog, key) ? renderDefaultValue(option) : (option.default ? "enabled" : "disabled");

      // The optional plugin-private scope suffix, appended to the description cell. Omitted cleanly when the hook returns `undefined`.
      const scopeSuffix = describeOptionScope?.(option, category) ?? "";

      // The full description cell: the option description, the bolded default, then any scope suffix. The description and the rendered default are catalog-derived plain
      // text and are escaped for safe table embedding; the scope suffix is hook-owned markup the plugin controls (e.g. a "<BR>") and passes through verbatim.
      const descriptionCell = escapeCellText(option.description) + " **(default: " + defaultCell + ")**." + scopeSuffix;

      return { descriptionCell, keyCell };
    });

    // The table primitive sizes the Option column from the widest rendered key cell and the heading in its single width pass, and draws the description-side divider
    // at this document's own constant. The rows stay flat and in catalog order - no group nesting - and the cells go in already rendered, so the padding is measured
    // on the anchored code span a reader actually sees.
    lines.push(...renderMarkdownTable({ dividerWidth: DESCRIPTION_DIVIDER_WIDTH, headings: [ "Option", "Description" ],
      rows: rows.map((row) => [ row.keyCell, row.descriptionCell ]) }));

    // A trailing blank line after each table separates it from the next section.
    lines.push("");
  }

  return lines.join("\n");
}

// The fixed scope sentences, keyed by the canonical form of the scope set that earns each one. The two entries are the two shapes a flat global-or-per-device hierarchy
// can declare; a set matching neither key looks up to `undefined`, which is exactly the "say nothing" answer the render hook wants, so the absent case needs no branch
// of its own. The leading "<BR>" is part of the sentence because the renderer concatenates a hook's return straight onto the description cell and passes hook-owned
// markup through verbatim, so the separator is the hook's to supply.
const FIXED_SCOPE_SENTENCES: Readonly<Record<string, string>> = {

  "device,global": "<BR>This option may be applied globally or on individual devices.",
  "global": "<BR>This option may only be applied globally."
};

// Reduce a scope declaration to a canonical key: deduplicated and sorted, so a set is compared as a set. A catalog is free to declare `[ "global", "device" ]` or
// `[ "device", "global" ]` for the same meaning, and neither reading should change the sentence.
function scopeSetKey(scopes: readonly FeatureOptionScope[]): string {

  return [...new Set(scopes)].sort().join(",");
}

/**
 * The pair of scope hooks {@link renderFeatureOptionsReference} accepts, as one value. A builder returns both together so a plugin's catalog module can destructure
 * them into the two exports it publishes, rather than assembling the pair itself.
 *
 * @typeParam TOptionMeta   - The concrete type of an option entry's opaque `meta` annotation.
 * @typeParam TCategoryMeta - The concrete type of a category entry's opaque `meta` annotation.
 *
 * @category Feature Options
 */
export interface ScopeDescribers<TOptionMeta = unknown, TCategoryMeta = unknown> {

  /**
   * The category-scope hook. Both builders return the honest no-op here: {@link FeatureCategoryEntry} declares no scopes at all, so there is nothing at the category
   * level to describe, and inventing an aggregation over a category's options would either restate the per-option suffixes or contradict a category whose options sit
   * at differing levels.
   */
  readonly describeCategoryScope: (category: FeatureCategoryEntry<TCategoryMeta>) => string | undefined;

  /**
   * The option-scope hook: the suffix appended to an option's description cell, or `undefined` to append nothing.
   */
  readonly describeOptionScope: (option: FeatureOptionEntry<TOptionMeta>, category: FeatureCategoryEntry<TCategoryMeta>) => string | undefined;
}

/**
 * What {@link buildComposedScopeDescribers} composes a sentence from.
 *
 * @category Feature Options
 */
export interface ComposedScopeOptions {

  /**
   * The word the sentence opens with, placed verbatim ahead of the list. Defaults to `"Configurable"`. Supply the capitalization you want: the frame positions this
   * word but does not transform it, so an override reading `"Set"` renders as `"Set"`.
   */
  readonly leadingWord?: string;

  /**
   * How the levels are joined when an option names more than one. `"disjunction"` renders "or" and is the default, matching what the fixed sentence's own "globally or
   * on individual devices" says: the levels an option MAY be configured at are alternatives, not a set that must all be used. `"conjunction"` renders "and" for a
   * hierarchy where naming them together reads better.
   */
  readonly listType?: "conjunction" | "disjunction";

  /**
   * The plugin's own name for each scope level, as a COMPLETE phrase carrying its own preposition - `"on each zone"`, `"at the controller level"`, `"globally"`. The
   * frame contributes the sentence mechanics around the list and nothing inside it, so a phrase reads correctly in any list position rather than only after whatever
   * preposition a shared frame happened to pick. Every level needs an entry: the record is total over {@link FeatureOptionScope}, so adding a level to the vocabulary
   * is a compiler error until every plugin names it.
   */
  readonly vocabulary: Readonly<Record<FeatureOptionScope, string>>;
}

/**
 * Build the scope hooks for a catalog whose options are configurable globally, or globally and per-device.
 *
 * These are the exact two sentences the family's flat-hierarchy plugins hand-wrote, and they are all this builder will say. An option declaring any other combination
 * of levels gets `undefined` rather than invented prose, because a sentence this builder does not have grounded copy for would be a sentence nobody wrote. A catalog
 * that lands there wants {@link buildComposedScopeDescribers} instead.
 *
 * @typeParam TOptionMeta   - The concrete type of an option entry's opaque `meta` annotation.
 * @typeParam TCategoryMeta - The concrete type of a category entry's opaque `meta` annotation.
 *
 * @returns The hook pair, ready to hand to {@link renderFeatureOptionsReference} or to re-export from a catalog module.
 *
 * @example
 *
 * ```ts
 * export const { describeCategoryScope, describeOptionScope } = buildFixedScopeDescribers<MyOptionMeta>();
 * ```
 *
 * @category Feature Options
 */
export function buildFixedScopeDescribers<TOptionMeta = unknown, TCategoryMeta = unknown>(): ScopeDescribers<TOptionMeta, TCategoryMeta> {

  return {

    describeCategoryScope: (): undefined => undefined,
    describeOptionScope: (option: FeatureOptionEntry<TOptionMeta>): string | undefined => {

      const scopes = option.scopes;

      // An unmatched set looks up to `undefined` from the sentence record, which is the same answer an absent declaration gets, so both cases land on "say nothing"
      // without a branch apiece.
      return scopes ? FIXED_SCOPE_SENTENCES[scopeSetKey(scopes)] : undefined;
    }
  };
}

/**
 * Build the scope hooks for a catalog whose hierarchy has more to say than "globally, or per device" - a controller tier, a domain name for the device tier, anything
 * the two fixed sentences cannot describe.
 *
 * The division of labor is what makes this shareable. The plugin owns the vocabulary: what each level is CALLED in the hierarchy its users see, as a self-contained
 * phrase. This owns the sentence around it: the opening word, the list grammar, the closing period, and the italic markup the family renders scope prose in. A plugin
 * therefore supplies the part only it can know and inherits the part that is the same everywhere.
 *
 * The list is rendered by `Intl.ListFormat` rather than by hand-joining, so two levels read "a or b" and three read "a, b, or c" without the caller owning that
 * grammar. The formatter is built once per builder call and reused across every option the render pass describes.
 *
 * @typeParam TOptionMeta   - The concrete type of an option entry's opaque `meta` annotation.
 * @typeParam TCategoryMeta - The concrete type of a category entry's opaque `meta` annotation.
 * @param options           - See {@link ComposedScopeOptions}.
 *
 * @returns The hook pair, ready to hand to {@link renderFeatureOptionsReference} or to re-export from a catalog module.
 *
 * @example
 *
 * ```ts
 * export const { describeCategoryScope, describeOptionScope } = buildComposedScopeDescribers<MyOptionMeta>({
 *
 *   vocabulary: { controller: "at the controller level", device: "on each zone", global: "globally" }
 * });
 *
 * // An option declaring [ "device", "global" ] renders: " <BR>*Configurable on each zone or globally.*"
 * ```
 *
 * @category Feature Options
 */
export function buildComposedScopeDescribers<TOptionMeta = unknown, TCategoryMeta = unknown>(
  options: ComposedScopeOptions): ScopeDescribers<TOptionMeta, TCategoryMeta> {

  const { leadingWord = "Configurable", listType = "disjunction", vocabulary } = options;

  // The locale is fixed rather than a parameter because the sentence this list sits inside is English: the leading word, the vocabulary phrases, and the punctuation
  // are all authored copy, and a list joined in another language's grammar would not match any of them.
  const listFormatter = new Intl.ListFormat("en", { style: "long", type: listType });

  return {

    describeCategoryScope: (): undefined => undefined,
    describeOptionScope: (option: FeatureOptionEntry<TOptionMeta>): string | undefined => {

      const scopes = option.scopes;

      if(!scopes) {

        return undefined;
      }

      return " <BR>*" + leadingWord + " " + listFormatter.format(scopes.map((scope) => vocabulary[scope])) + ".*";
    }
  };
}
