/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * featureOptions-docs.ts: Pure, isomorphic renderer that projects a feature-options catalog into the markdown reference each plugin ships in its docs.
 */

/**
 * A shared documentation renderer for the {@link featureOptions!FeatureOptions | FeatureOptions} catalog.
 *
 * Every plugin in the family used to ship a near-duplicate `*-gendocs.ts` script that walked its feature-options catalog and printed a markdown category index plus
 * per-category option tables, then pasted the result into its `docs/FeatureOptions.md` by hand. ~95% of each script was identical, and each hand-rolled the dotted-key
 * construction and the value-vs-toggle discrimination that this library already owns as single-source-of-truth helpers. This module collapses all of that into one
 * elegant renderer so the documentation becomes a pure projection of the live catalog.
 *
 * The module exports two pure string functions:
 *
 *   - {@link renderFeatureOptionsReference} - the projection itself. It derives every key via {@link expandOption}, decides value-ness via {@link isValueOption}, and
 *     builds the catalog index once via {@link buildCatalogIndex}; it never re-derives any of those. Plugin-private scope prose is supplied through two optional render
 *     hooks that mirror the webUI's field-blind `validOption` / `validOptionCategory` predicate seam, lifted from *filter* (boolean) to *describe* (string). No
 *     plugin-specific field name appears anywhere in this file.
 *
 *   - {@link spliceMarkedRegion} - the in-place splice that replaces the region between {@link FEATURE_OPTIONS_DOC_BEGIN} / {@link FEATURE_OPTIONS_DOC_END} in an
 *     existing doc with freshly rendered content, leaving each plugin's hand-written header and intro untouched.
 *
 * Both functions are pure and isomorphic: no `node:` imports, no `fs`, no `process`. The only I/O - reading the doc and writing it back - is two lines of
 * `node:fs/promises` in each plugin's build-script shim, which is inherently a tooling concern. This module is therefore browser-safe and trivially testable, but it
 * is a tooling concern and is deliberately NOT mirrored into `dist/ui/` by the build pipeline.
 *
 * @module
 */
import type { FeatureCategoryEntry, FeatureOptionEntry } from "./featureOptions.ts";
import { buildCatalogIndex, expandOption, isValueOption } from "./featureOptions.ts";

/**
 * The opening marker of the auto-generated region in a plugin's `docs/FeatureOptions.md`. {@link spliceMarkedRegion} replaces everything strictly between this marker
 * and {@link FEATURE_OPTIONS_DOC_END}, preserving both markers and the hand-written prose around them. The text doubles as an in-document warning to maintainers not to
 * edit the region by hand.
 *
 * @category Feature Options
 */
export const FEATURE_OPTIONS_DOC_BEGIN = "<!-- FEATURE OPTIONS:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated region. See {@link FEATURE_OPTIONS_DOC_BEGIN}.
 *
 * @category Feature Options
 */
export const FEATURE_OPTIONS_DOC_END = "<!-- FEATURE OPTIONS:END -->";

// The fixed width, in dashes, of the description-side divider segment. The Option-side width is auto-computed per table from the visible cell widths; the
// description side has no upper bound worth chasing (descriptions plus scope suffixes can be arbitrarily long), so it is a sensible constant rather than a second
// max pass. Padding is cosmetic - rendered markdown ignores it - so this is presentation polish, not part of the semantic contract.
const DESCRIPTION_DIVIDER_WIDTH = 61;

// One trailing space of breathing room added to the auto-computed Option-column width so the widest key cell does not sit flush against the column separator. Purely
// cosmetic alignment, matching the canonical rendering the family converges on.
const OPTION_COLUMN_PADDING = 1;

// The substitution shown in the default cell for a value option whose declared default is the empty string. We render "none" rather than an empty cell so the table
// communicates "this option defaults to no value" explicitly. The substitution happens at render time only; the catalog entry is never mutated.
const EMPTY_DEFAULT_LABEL = "none";

// Escape catalog-derived plain text for safe embedding in a markdown table cell, heading, or index line. We neutralize the column separator "|" (which would inject
// a phantom table column) and the HTML-significant "&", "<", ">" (which would otherwise be parsed as markup and swallowed). "&" is replaced first so the entities we
// introduce are not themselves re-escaped. This is applied ONLY to catalog-derived plain text (descriptions and the rendered default value); it is deliberately NOT
// applied to the dotted key (a constrained identifier that also lives inside a code span where entities would not decode), to the renderer's own structural HTML
// (the per-row/heading anchors) or the ".<value>" placeholder, nor to the scope-hook return values (the plugin owns that markup - e.g. a "<BR>" line break).
function escapeCellText(text: string): string {

  return text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("|", "\\|");
}

/**
 * Render a feature-options catalog into the markdown reference fragment a plugin embeds in its `docs/FeatureOptions.md`. The output is a category index (one bullet per
 * category, deep-linking to its detail section), an optional one-line legend explaining the `.<value>` notation, and then one detail section per category, each carrying
 * an optional device-scope line and a flat table of option rows. The legend is emitted only when the catalog has at least one value option, since a toggle-only catalog
 * never renders the `.<value>` placeholder the legend describes.
 *
 * The renderer owns all base-shaped scaffolding - the index, headings, per-row deep-link anchors, the key cell with its value/toggle placeholder, the default cell, the
 * description cell, and the column math - purely from the base {@link FeatureOptionEntry} / {@link FeatureCategoryEntry} fields. The two optional hooks own *only* the
 * plugin-private scope prose: `describeCategoryScope` contributes the device-scope sentence under a category heading, and `describeOptionScope` contributes a suffix
 * appended to an option's description cell. A hook returning `undefined` omits its contribution cleanly - never an "undefined" literal, never a stray blank line.
 *
 * The catalog index is built once via {@link buildCatalogIndex}; value-ness is decided via {@link isValueOption}; the canonical dotted key is derived via
 * {@link expandOption}. None of those is re-derived here - the renderer is a projection of the same single source of truth the rest of the module owns.
 *
 * @typeParam TOptionMeta   - The concrete type of an option entry's opaque `meta` annotation, reconstituted at this boundary so `describeOptionScope` sees it typed.
 * @typeParam TCategoryMeta - The concrete type of a category entry's opaque `meta` annotation, reconstituted so `describeCategoryScope` sees it typed.
 * @param input
 * @param input.categories            - The catalog's category list, in the order the index and detail sections should follow.
 * @param input.describeCategoryScope - Optional. Returns the device-scope sentence emitted under a category's heading, or `undefined` to omit it. The hook owns the full
 *                                      sentence including any leading or trailing text.
 * @param input.describeOptionScope   - Optional. Returns a suffix appended to an option's description cell, or `undefined` to omit it. The hook owns its full text
 *                                      including any leading separator.
 * @param input.options               - The catalog's options map keyed by category name.
 *
 * @returns The rendered markdown fragment.
 */
export function renderFeatureOptionsReference<TOptionMeta = unknown, TCategoryMeta = unknown>(input: {
  categories: readonly FeatureCategoryEntry<TCategoryMeta>[];
  describeCategoryScope?: (category: FeatureCategoryEntry<TCategoryMeta>) => string | undefined;
  describeOptionScope?: (option: FeatureOptionEntry<TOptionMeta>, category: FeatureCategoryEntry<TCategoryMeta>) => string | undefined;
  options: Readonly<Record<string, readonly FeatureOptionEntry<TOptionMeta>[]>>;
}): string {

  const { categories, describeCategoryScope, describeOptionScope, options } = input;

  // Build the catalog index once. We never re-derive value-options, defaults, or the dotted key downstream - everything routes back through this single source of
  // truth. The index accepts the typed arrays because a parameterized entry is structurally assignable to the base entry the index is declared over.
  const catalog = buildCatalogIndex(categories, options);

  // Accumulate the rendered lines. We assemble line-by-line and join with newlines at the end rather than concatenating strings, which keeps the blank-line discipline
  // explicit (a pushed empty string is a blank line) and avoids a forest of "\n" literals.
  const lines: string[] = [];

  // Index pass: one bullet per category, deep-linking to the category's detail heading. We iterate the typed `categories` array directly - not `catalog.categories`,
  // which is base-typed - and apply the same "skip a category with no options entry" rule the index builder uses, so the two traversals cannot disagree. The bullet's
  // link text is the category name; the anchor is its lowercased form; the trailing text is the category description verbatim, with no appended suffix.
  for(const category of categories) {

    if(!options[category.name]) {

      continue;
    }

    lines.push(" * [" + category.name + "](#" + category.name.toLowerCase() + "): " + escapeCellText(category.description));
  }

  // A single blank line separates the index from the detail sections.
  lines.push("");

  // Conditional legend. When the catalog has at least one value option, we explain the renderer's own ".<value>" notation - the suffix it appends to value-option keys -
  // so a reader knows to substitute their setting rather than typing the literal placeholder, and that every other option is a simple on/off toggle. The legend is
  // suppressed for a toggle-only catalog (no value options) where the ".<value>" notation never appears, so the explanation would document a notation the reader never
  // sees. It sits after the index's trailing blank line and is itself followed by a blank line, keeping it cleanly framed before the first detail heading.
  if(catalog.sortedValueOptionNames.length > 0) {

    lines.push("Options whose key ends in `.<value>` take a value - replace `.<value>` with your setting; all other options are simple on/off toggles. " +
      "The default shown for each option is what applies when you leave it unset.");
    lines.push("");
  }

  // Detail pass: one section per category, in catalog order.
  for(const category of categories) {

    const categoryOptions = options[category.name];

    // Skip a category with no options entry, matching the index builder's rule so the detail traversal stays in lockstep with the index.
    if(!categoryOptions) {

      continue;
    }

    // Heading with an invisible anchor so the index bullets can deep-link to it. The visible text is the category description, verbatim.
    lines.push("#### <A NAME=\"" + category.name.toLowerCase() + "\"></A>" + escapeCellText(category.description));
    lines.push("");

    // Optional device-scope line. The hook owns the full sentence; when it returns `undefined` we omit the line and its trailing blank line entirely rather than
    // emitting an empty row or the literal string "undefined".
    const categoryScope = describeCategoryScope?.(category);

    if(categoryScope !== undefined) {

      lines.push(categoryScope);
      lines.push("");
    }

    // Compose each option's two cells - the key cell and the description cell - up front so we can size the Option column to the widest visible key cell before we
    // emit any table line. This is the single max pass the column math needs; nothing downstream re-walks the options.
    const rows = categoryOptions.map((option) => {

      // The canonical dotted key (single source of truth - never hand-concatenated). For a category-level option (empty name), `expandOption` returns the category
      // name alone, which is exactly the bare-category key we want to render.
      const key = expandOption(category, option);

      // The key cell pairs an invisible per-row anchor (key case preserved, so deep links are stable) with a single backtick code span. Value-ness is signaled
      // lexically by appending the universal ".<value>" placeholder inside the same span - no mixed HTML, faithful to the template the user fills in.
      const keyCell = "<A NAME=\"" + key + "\"></A>`" + key + (isValueOption(catalog, key) ? ".<value>" : "") + "`";

      // The default cell. A value option shows its raw declared default in the form the user would type - never formatted, since a formatted value (e.g. "30s") is an
      // invalid config value. The empty-string default substitutes to "none" at render time, without mutating the entry. A toggle shows enabled / disabled.
      const defaultCell = isValueOption(catalog, key) ?
        (((option.defaultValue ?? "") === "") ? EMPTY_DEFAULT_LABEL : escapeCellText(String(option.defaultValue))) :
        (option.default ? "enabled" : "disabled");

      // The optional plugin-private scope suffix, appended to the description cell. Omitted cleanly when the hook returns `undefined`.
      const scopeSuffix = describeOptionScope?.(option, category) ?? "";

      // The full description cell: the option description, the bolded default, then any scope suffix. The description and the rendered default are catalog-derived plain
      // text and are escaped for safe table embedding; the scope suffix is hook-owned markup the plugin controls (e.g. a "<BR>") and passes through verbatim.
      const descriptionCell = escapeCellText(option.description) + " **(default: " + defaultCell + ")**." + scopeSuffix;

      return { descriptionCell, keyCell };
    });

    // Auto-compute the Option-column width from the widest visible key cell and the header label, plus one space of breathing room. Padding is cosmetic - rendered
    // markdown collapses it - so this is alignment polish for the raw source, not part of the semantic contract.
    const optionColumnWidth = rows.reduce((width, row) => Math.max(width, row.keyCell.length), "Option".length) + OPTION_COLUMN_PADDING;

    // Table header and divider. The Option-side divider width tracks the computed column (plus the two single-space gutters around the cell); the description-side
    // divider is the fixed constant.
    lines.push("| " + "Option".padEnd(optionColumnWidth) + " | Description");
    lines.push("|" + "-".repeat(optionColumnWidth + 2) + "|" + "-".repeat(DESCRIPTION_DIVIDER_WIDTH));

    // One flat row per option, in catalog order. No group nesting - the rows are flat by design.
    for(const row of rows) {

      lines.push("| " + row.keyCell.padEnd(optionColumnWidth) + " | " + row.descriptionCell);
    }

    // A trailing blank line after each table separates it from the next section.
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Replace the region strictly between {@link FEATURE_OPTIONS_DOC_BEGIN} and {@link FEATURE_OPTIONS_DOC_END} in `source` with `content`, leaving both markers and all
 * surrounding prose untouched. This is the pure half of the in-place splice each plugin's build-script shim performs; the shim supplies the trivial `readFile` /
 * `writeFile` around it.
 *
 * The replacement inserts a newline before and after `content`, so a marker pair on its own lines stays on its own lines and the rendered fragment is cleanly framed.
 * The operation is idempotent: splicing the same `content` into an already-spliced document reproduces it byte-for-byte. Each marker may be overridden through the
 * options object for documents that use a different convention, though the defaults match what every plugin in the family embeds.
 *
 * @param source            - The full document text.
 * @param content           - The fragment to insert between the markers, typically the output of {@link renderFeatureOptionsReference}.
 * @param markers
 * @param markers.beginMarker - The opening marker to search for. Defaults to {@link FEATURE_OPTIONS_DOC_BEGIN}.
 * @param markers.endMarker   - The closing marker to search for. Defaults to {@link FEATURE_OPTIONS_DOC_END}.
 *
 * @returns `source` with the marked region's contents replaced by `content`.
 *
 * @throws `Error` naming the offending marker when either marker is absent, when the closing marker precedes the opening marker, or when the document is ambiguous - a
 *         second begin marker after the first, or a second end marker - since the marked region would not be uniquely identified.
 */
export function spliceMarkedRegion(source: string, content: string,
  { beginMarker = FEATURE_OPTIONS_DOC_BEGIN, endMarker = FEATURE_OPTIONS_DOC_END }: { beginMarker?: string; endMarker?: string } = {}): string {

  const beginIndex = source.indexOf(beginMarker);

  if(beginIndex === -1) {

    throw new Error("spliceMarkedRegion: begin marker not found in source: \"" + beginMarker + "\".");
  }

  const endIndex = source.indexOf(endMarker);

  if(endIndex === -1) {

    throw new Error("spliceMarkedRegion: end marker not found in source: \"" + endMarker + "\".");
  }

  // The opening marker must come before the closing marker. We compare against the end of the begin marker so an end marker that overlaps or sits immediately after
  // the begin marker is still rejected as malformed rather than producing a negative-length region.
  const regionStart = beginIndex + beginMarker.length;

  if(endIndex < regionStart) {

    throw new Error("spliceMarkedRegion: end marker \"" + endMarker + "\" precedes begin marker \"" + beginMarker + "\" in source.");
  }

  // Reject an ambiguous document. A second begin marker after the first - or a second end marker anywhere - means the marked region is not uniquely identified, and
  // splicing into the first pair would silently leave the duplicate marker (and any stale content between the duplicates) behind. We search from just past the end of
  // the first occurrence (the `includes` fromIndex argument) so an exact re-find of the same marker is not mistaken for a duplicate.
  if(source.includes(beginMarker, beginIndex + beginMarker.length)) {

    throw new Error("spliceMarkedRegion: multiple begin markers found in source; the marked region is ambiguous.");
  }

  if(source.includes(endMarker, endIndex + endMarker.length)) {

    throw new Error("spliceMarkedRegion: multiple end markers found in source; the marked region is ambiguous.");
  }

  // Reassemble: everything up to and including the begin marker, a newline-framed copy of the new content, then everything from the end marker onward.
  return source.slice(0, regionStart) + "\n" + content + "\n" + source.slice(endIndex);
}
