/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * mqtt-topics-docs.ts: Pure, isomorphic renderer that projects an MQTT topic catalog into the two tables a plugin ships in its MQTT documentation.
 */

/**
 * A shared documentation renderer for the {@link mqtt-topics!MqttTopicCatalog | MqttTopicCatalog} a plugin declares its topic surface in.
 *
 * Every plugin in the family hand-writes the two tables in its `docs/MQTT.md`, and the drift that produces is exactly what a hand-maintained second copy of a
 * declaration always produces: a topic the code never publishes, a topic the code publishes and the document never mentions, a publish sentence copied under a get
 * row. Projecting both tables from the catalog the call sites already read makes every one of those unrepresentable rather than corrected.
 *
 * One call renders both sections, because one traversal validates the catalog and emits the rows either section takes. Each section is a fragment for a marked
 * region of its own - {@link MQTT_PUBLISHED_DOC_BEGIN} and {@link MQTT_SUBSCRIBED_DOC_BEGIN} name them - rather than one region spanning both, so a plugin keeps its
 * H3 headings, their lead sentences, and every hand-written section around and between the two tables. A section the catalog declares no rows for renders as an
 * empty fragment: a publish-only plugin's subscribed region carries no table, and the plugin writes no heading above a region it declares nothing for.
 *
 * What each table carries is the entry's own declaration. An entry contributes a published row when it declares `publish`, a subscribed row for its get child when it
 * declares `get`, and another for its set child when it declares `set`, so the document says exactly what the plugin does. A row credits the kinds its verb's narrowing
 * names, and the entry's whole list when the verb has none. The column layout, the width pass, and the divider are
 * {@link doc-markdown!renderMarkdownTable | renderMarkdownTable}'s; this module owns which cells go into it and how each one reads.
 *
 * The renderer is pure and isomorphic: no `node:` imports, no `fs`, no `process`. The only I/O - reading the document and writing it back - belongs to the
 * `prepare-mqtt` verb that drives it. This module is therefore browser-safe and trivially testable, but it is a tooling concern and is deliberately NOT mirrored
 * into `dist/ui/` by the build pipeline.
 *
 * @module
 */
import { MQTT_DEVICE_COLUMN, mqttGetTopic, mqttSetTopic, mqttTopicPlaceholders, resolveMqttTopic } from "./mqtt-topics.ts";
import type { MqttTopicCatalog, MqttTopicDeviceColumn, MqttTopicEntry } from "./mqtt-topics.ts";
import { renderMarkdownTable } from "./doc-markdown.ts";

/**
 * The opening marker of the auto-generated published-topics region in a plugin's `docs/MQTT.md`. The documentation module's
 * {@link doc-markdown!spliceMarkedRegion | spliceMarkedRegion} replaces everything strictly between this marker and {@link MQTT_PUBLISHED_DOC_END}, preserving both
 * markers and the hand-written prose around them. The text doubles as an in-document warning to maintainers not to edit the region by hand.
 *
 * @category Utilities
 */
export const MQTT_PUBLISHED_DOC_BEGIN = "<!-- MQTT PUBLISHED:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated published-topics region. See {@link MQTT_PUBLISHED_DOC_BEGIN}.
 *
 * @category Utilities
 */
export const MQTT_PUBLISHED_DOC_END = "<!-- MQTT PUBLISHED:END -->";

/**
 * The opening marker of the auto-generated subscribed-topics region. Its own pair rather than a continuation of the published one, so a plugin's prose between the
 * two sections stays the plugin's.
 *
 * @category Utilities
 */
export const MQTT_SUBSCRIBED_DOC_BEGIN = "<!-- MQTT SUBSCRIBED:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated subscribed-topics region. See {@link MQTT_SUBSCRIBED_DOC_BEGIN}.
 *
 * @category Utilities
 */
export const MQTT_SUBSCRIBED_DOC_END = "<!-- MQTT SUBSCRIBED:END -->";

/**
 * The two fragments {@link renderMqttTopicsReference} produces, one per marked region.
 *
 * @property published  - The published-topics tables, for the region {@link MQTT_PUBLISHED_DOC_BEGIN} opens.
 * @property subscribed - The subscribed-topics tables, for the region {@link MQTT_SUBSCRIBED_DOC_BEGIN} opens.
 *
 * @category Utilities
 */
export interface MqttTopicsReference {

  readonly published: string;
  readonly subscribed: string;
}

// The fixed width, in dashes, of the message-side divider segment this document prints. The topic and device columns are auto-computed per table from the visible
// cell widths; the message side has no upper bound worth chasing, so it is a presentation constant of this document exactly as its counterpart is of the
// feature-options reference. Padding is cosmetic - rendered markdown ignores it - so this is polish, not part of the semantic contract.
const MESSAGE_DIVIDER_WIDTH = 34;

// What joins the device labels inside one cell.
const LABEL_SEPARATOR = ", ";

// The verbs a row can carry, the field each one reads its narrowing from, and the fields whose presence needs a column to mean anything. They are spelled once here
// so the checks and the cells run from one list rather than from separate copies of the same names.
const VERBS = [ "get", "publish", "set" ] as const;

type TopicVerb = (typeof VERBS)[number];

type NarrowingField = "getDevices" | "publishDevices" | "setDevices";

const NARROWING_FIELDS: Readonly<Record<TopicVerb, NarrowingField>> = { get: "getDevices", publish: "publishDevices", set: "setDevices" };

const COLUMN_FIELDS: readonly ("devices" | NarrowingField)[] = [ "devices", ...VERBS.map((verb) => NARROWING_FIELDS[verb]) ];

// One rendered row: the cells its table prints in column order, the group it renders under, and the segments the section sorts it on. The row keeps its entry's own
// topic, as segments, beside the rendered cells because the sort walks the topic tree rather than the printed text: markup would sort every parameterized topic into
// a block of its own, and the printed child of one topic would sort behind the printed child of a topic beneath it.
interface TopicRow {

  readonly cells: readonly string[];
  readonly group?: string;
  readonly segments: readonly string[];
}

// Neutralize the column separator in author-owned markdown. A bare "|" would open a phantom column, while backticks, links, and alert markup have to reach the
// document exactly as the plugin wrote them - so this is the only transformation a message text or a device label receives.
function escapeColumnSeparator(text: string): string {

  return text.replaceAll("|", "\\|");
}

// Render a raw topic as the document shows it. A plain tail sits in a backtick code span; a template becomes an HTML code span so each placeholder can be italicized
// in place, which markdown offers no way to do inside a backtick span. The substitution goes through the resolver, so the markup form and the wire form are produced
// by one statement of what a placeholder is.
function renderTopicCell(topic: string): string {

  const placeholders = mqttTopicPlaceholders(topic);

  if(placeholders.length === 0) {

    return "`" + topic + "`";
  }

  return "<CODE>" + resolveMqttTopic(topic, Object.fromEntries(placeholders.map((name) => [ name, "<I>" + name + "</I>" ]))) + "</CODE>";
}

// Validate an entry's device declaration and every narrowing it carries against the catalog's column, then derive the cell each verb's row prints. The column and
// the lists are one decision, so both directions are checked here: with a column every entry names at least one kind the vocabulary declares, and without one no
// entry names any, its narrowings included. A verb's cell names the kinds its narrowing lists, or the entry's whole list when the verb declares no narrowing, and
// the labels are joined in the vocabulary's declared order rather than the entry's, so one declaration fixes how every cell in the column reads.
function renderDeviceCells({ column, entry, key }: {

  column: MqttTopicDeviceColumn | undefined;
  entry: MqttTopicEntry;
  key: string;
}): Readonly<Record<TopicVerb, string>> {

  if(column === undefined) {

    const strayField = COLUMN_FIELDS.find((field) => entry[field] !== undefined);

    if(strayField !== undefined) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " declares " + strayField + " but the catalog declares no column.");
    }

    return { get: "", publish: "", set: "" };
  }

  const devices = entry.devices;

  if((devices === undefined) || (devices.length === 0)) {

    throw new Error("renderMqttTopicsReference: the column \"" + column.heading + "\" needs a devices list on the entry " + key + ".");
  }

  for(const device of devices) {

    if(!(device in column.vocabulary)) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " names a device \"" + device + "\" the column's vocabulary does not declare.");
    }
  }

  for(const verb of VERBS) {

    const field = NARROWING_FIELDS[verb];
    const narrowing = entry[field];

    if(narrowing === undefined) {

      continue;
    }

    if(entry[verb] === undefined) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " declares " + field + " but no " + verb + ".");
    }

    if(narrowing.length === 0) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " declares an empty " + field + " list.");
    }

    const stray = narrowing.find((device) => !devices.includes(device));

    if(stray !== undefined) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " names a device \"" + stray + "\" in " + field + " that its devices list does not carry.");
    }
  }

  // A kind the entry lists but no verb it declares performs is a kind the document would print without ever saying what it does, which is the mistake the whole
  // narrowing exists to let an author avoid rather than introduce.
  const credited = new Set(VERBS.filter((verb) => entry[verb] !== undefined).flatMap((verb) => entry[NARROWING_FIELDS[verb]] ?? devices));
  const uncredited = devices.find((device) => !credited.has(device));

  if(uncredited !== undefined) {

    throw new Error("renderMqttTopicsReference: the entry " + key + " lists a device \"" + uncredited + "\" that none of its verbs credits.");
  }

  const labels = Object.entries(column.vocabulary);
  const cellFor = (kinds: readonly string[]): string => {

    return escapeColumnSeparator(labels.filter(([name]) => kinds.includes(name)).map(([ , label ]) => label).join(LABEL_SEPARATOR));
  };

  return { get: cellFor(entry.getDevices ?? devices), publish: cellFor(entry.publishDevices ?? devices), set: cellFor(entry.setDevices ?? devices) };
}

// Build one row from an entry's declaration. The message text and the device labels are author-owned markdown and receive only the separator escape; the topic cell
// is this module's own markup.
function buildRow({ deviceCell, group, message, segments, topic, withColumn }: {

  deviceCell: string;
  group?: string;
  message: string;
  segments: readonly string[];
  topic: string;
  withColumn: boolean;
}): TopicRow {

  const cells = withColumn ? [ renderTopicCell(topic), deviceCell, escapeColumnSeparator(message) ] :
    [ renderTopicCell(topic), escapeColumnSeparator(message) ];

  return { cells, group, segments };
}

// Order two rows as the topic tree reads: at the first segment where two topics differ the lower segment comes first, and a topic that is the prefix of another comes
// ahead of it, so a topic precedes every topic that extends it. Comparing the printed text would sort a hyphenated sibling ahead of its base topic's rows, because a
// hyphen sorts below a slash, and it would sort a topic's own get and set rows behind the rows of the topics beneath it. Two rows on one topic tie, and the tie needs
// no second key: the traversal pushes an entry's get row before its set row and `toSorted` is stable, so one entry's two subscribed rows keep that order, and two
// entries that produce one wire topic keep their declared order.
function byTopicTree(left: TopicRow, right: TopicRow): number {

  for(const [ index, leftSegment ] of left.segments.entries()) {

    const rightSegment = right.segments[index];

    // Every segment so far matched and the right topic has run out, so it is the shorter of two topics on one branch and belongs ahead of this one.
    if(rightSegment === undefined) {

      return 1;
    }

    if(leftSegment !== rightSegment) {

      return (leftSegment < rightSegment) ? -1 : 1;
    }
  }

  // The left topic matched through its whole length, so it is either the same topic or the prefix of a longer one, which it precedes.
  return (left.segments.length < right.segments.length) ? -1 : 0;
}

// Render one section: a single table for an ungrouped catalog, or one table per group that has rows in this section, each under its own H4 heading. Nothing to list
// renders nothing, at either level - a section the catalog has no rows for is an empty fragment, and a group with no rows in this section is left out of it - so a
// plugin never gets a heading, a divider, or a header row standing over nothing.
function renderSection(rows: readonly TopicRow[], groups: readonly string[], headings: readonly string[]): string {

  if(rows.length === 0) {

    return "";
  }

  const lines: string[] = [];

  if(groups.length === 0) {

    lines.push(...renderMarkdownTable({ dividerWidth: MESSAGE_DIVIDER_WIDTH, headings, rows: rows.map((row) => row.cells) }));
    lines.push("");

    return lines.join("\n");
  }

  for(const group of groups) {

    const groupRows = rows.filter((row) => row.group === group);

    if(groupRows.length === 0) {

      continue;
    }

    lines.push("#### " + group);
    lines.push("");
    lines.push(...renderMarkdownTable({ dividerWidth: MESSAGE_DIVIDER_WIDTH, headings, rows: groupRows.map((row) => row.cells) }));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Render an MQTT topic catalog into the two markdown fragments a plugin embeds in its `docs/MQTT.md`: the published-topics tables and the subscribed-topics tables.
 *
 * One traversal validates the catalog and emits both sections' rows. The validation is the document's own, not the builder's: the compiled JavaScript the CLI loads
 * carries no types, so the checks a declaration's shape would otherwise make at compile time are made here instead, and a documentation mistake fails the docs
 * build rather than a plugin's startup. Every message names the offending entry by key.
 *
 * Rows are ordered as the topic tree reads - a topic before every topic that extends it, siblings in plain order, and a topic's own get and set rows before the rows
 * of the topics beneath it - grouped when the catalog declares groups, and given a device column when the catalog declares one, with each entry's labels joined in
 * the order the vocabulary declares them. A row's device cell names the kinds its verb's narrowing lists, or the entry's whole list when the verb declares none. A
 * section the catalog has no rows for is an empty string.
 *
 * @param catalog - The catalog to project, as {@link mqtt-topics!mqttTopicCatalog | mqttTopicCatalog} returned it.
 *
 * @returns The two fragments, one per marked region.
 *
 * @throws `Error` naming the offending entry when the catalog declares a column without a string heading or a vocabulary object, when a column is declared and an
 *         entry carries no devices list or names a kind the vocabulary does not declare, when no column is declared and an entry carries a devices list or a verb's
 *         narrowing, when a narrowing is declared without its verb's own message text, when a narrowing is empty or names a kind the entry's devices list does not
 *         carry, when a kind the entry lists is credited by none of the verbs it declares, or when some entries declare a group and others do not.
 *
 * @category Utilities
 */
export function renderMqttTopicsReference(catalog: MqttTopicCatalog): MqttTopicsReference {

  const column = catalog[MQTT_DEVICE_COLUMN];

  if(column !== undefined) {

    // The CLI loads a plugin's COMPILED catalog, and compiled JavaScript carries no types, so the column arrives as whatever that module exported. These two checks
    // are the ones the declaration's own type would have made at authoring time, made here instead - which is why the column is read through a view that admits the
    // shapes the type says cannot occur.
    const declared: { heading?: unknown; vocabulary?: unknown } = column;

    if(typeof declared.heading !== "string") {

      throw new Error("renderMqttTopicsReference: the catalog's device column declares no heading text.");
    }

    if((typeof declared.vocabulary !== "object") || (declared.vocabulary === null)) {

      throw new Error("renderMqttTopicsReference: the catalog's device column \"" + column.heading + "\" declares no vocabulary object.");
    }
  }

  const published: TopicRow[] = [];
  const subscribed: TopicRow[] = [];
  const groups: string[] = [];

  // The first entry sets the catalog's grouping expectation, and the first entry that departs from it is named against that one - a rule with no tie to break.
  let expectation: { grouped: boolean; key: string } | undefined;

  for(const [ key, entry ] of Object.entries(catalog)) {

    const cells = renderDeviceCells({ column, entry, key });
    const segments = entry.topic.split("/");
    const grouped = entry.group !== undefined;

    expectation ??= { grouped, key };

    if(expectation.grouped !== grouped) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " declares " + (grouped ? "a group while the entry " : "no group while the entry ") +
        expectation.key + (grouped ? " declares none." : " declares one."));
    }

    if((entry.group !== undefined) && !groups.includes(entry.group)) {

      groups.push(entry.group);
    }

    const withColumn = column !== undefined;

    if(entry.publish !== undefined) {

      published.push(buildRow({ deviceCell: cells.publish, group: entry.group, message: entry.publish, segments, topic: entry.topic, withColumn }));
    }

    if(entry.get !== undefined) {

      subscribed.push(buildRow({ deviceCell: cells.get, group: entry.group, message: entry.get, segments, topic: mqttGetTopic(entry.topic), withColumn }));
    }

    if(entry.set !== undefined) {

      subscribed.push(buildRow({ deviceCell: cells.set, group: entry.group, message: entry.set, segments, topic: mqttSetTopic(entry.topic), withColumn }));
    }
  }

  const leadingHeadings = (column === undefined) ? ["Topic"] : [ "Topic", column.heading ];

  return {

    published: renderSection(published.toSorted(byTopicTree), groups, [ ...leadingHeadings, "Message Published" ]),
    subscribed: renderSection(subscribed.toSorted(byTopicTree), groups, [ ...leadingHeadings, "Message Expected" ])
  };
}
