/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * mqtt-topics-docs.ts: Pure, isomorphic renderer that projects an MQTT topic catalog into the two tables a plugin ships in its MQTT documentation.
 */

/**
 * A shared documentation renderer for the {@link mqtt-topics!MqttTopicCatalog | MqttTopicCatalog} a plugin declares its topic surface in.
 *
 * Every plugin in the family hand-writes the two tables in its `docs/MQTT.md`, and the drift that produces is exactly what a hand-maintained second copy of a
 * declaration always produces: a topic the code never publishes, a topic the code publishes and the document never mentions, a publish sentence copied under a get
 * row. Projecting both tables from the catalog the call sites already read makes every one of those unrepresentable rather than corrected.
 *
 * One call renders both sections, because one traversal validates the catalog and emits the rows either section takes. Each section is a fragment for a marked
 * region of its own - {@link MQTT_PUBLISHED_DOC_BEGIN} and {@link MQTT_SUBSCRIBED_DOC_BEGIN} name them - rather than one region spanning both, so a plugin keeps its
 * H3 headings, their lead sentences, and every hand-written section around and between the two tables. A section the catalog declares no rows for renders as an
 * empty fragment: a publish-only plugin's subscribed region carries no table, and the plugin writes no heading above a region it declares nothing for.
 *
 * What each table carries is the entry's own declaration. An entry contributes a published row when it declares `publish`, a subscribed row for its get child when
 * it declares `get`, and another for its set child when it declares `set`, so the document says exactly what the plugin does. The column layout, the width pass,
 * and the divider are {@link doc-markdown!renderMarkdownTable | renderMarkdownTable}'s; this module owns which cells go into it and how each one reads.
 *
 * The renderer is pure and isomorphic: no `node:` imports, no `fs`, no `process`. The only I/O - reading the document and writing it back - belongs to the
 * `prepare-mqtt` verb that drives it. This module is therefore browser-safe and trivially testable, but it is a tooling concern and is deliberately NOT mirrored
 * into `dist/ui/` by the build pipeline.
 *
 * @module
 */
import { MQTT_DEVICE_COLUMN, mqttGetTopic, mqttSetTopic, mqttTopicPlaceholders, resolveMqttTopic } from "./mqtt-topics.ts";
import type { MqttTopicCatalog, MqttTopicDeviceColumn, MqttTopicEntry } from "./mqtt-topics.ts";
import { renderMarkdownTable } from "./doc-markdown.ts";

/**
 * The opening marker of the auto-generated published-topics region in a plugin's `docs/MQTT.md`. The documentation module's
 * {@link doc-markdown!spliceMarkedRegion | spliceMarkedRegion} replaces everything strictly between this marker and {@link MQTT_PUBLISHED_DOC_END}, preserving both
 * markers and the hand-written prose around them. The text doubles as an in-document warning to maintainers not to edit the region by hand.
 *
 * @category Utilities
 */
export const MQTT_PUBLISHED_DOC_BEGIN = "<!-- MQTT PUBLISHED:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated published-topics region. See {@link MQTT_PUBLISHED_DOC_BEGIN}.
 *
 * @category Utilities
 */
export const MQTT_PUBLISHED_DOC_END = "<!-- MQTT PUBLISHED:END -->";

/**
 * The opening marker of the auto-generated subscribed-topics region. Its own pair rather than a continuation of the published one, so a plugin's prose between the
 * two sections stays the plugin's.
 *
 * @category Utilities
 */
export const MQTT_SUBSCRIBED_DOC_BEGIN = "<!-- MQTT SUBSCRIBED:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated subscribed-topics region. See {@link MQTT_SUBSCRIBED_DOC_BEGIN}.
 *
 * @category Utilities
 */
export const MQTT_SUBSCRIBED_DOC_END = "<!-- MQTT SUBSCRIBED:END -->";

/**
 * The two fragments {@link renderMqttTopicsReference} produces, one per marked region.
 *
 * @property published  - The published-topics tables, for the region {@link MQTT_PUBLISHED_DOC_BEGIN} opens.
 * @property subscribed - The subscribed-topics tables, for the region {@link MQTT_SUBSCRIBED_DOC_BEGIN} opens.
 *
 * @category Utilities
 */
export interface MqttTopicsReference {

  readonly published: string;
  readonly subscribed: string;
}

// The fixed width, in dashes, of the message-side divider segment this document prints. The topic and device columns are auto-computed per table from the visible
// cell widths; the message side has no upper bound worth chasing, so it is a presentation constant of this document exactly as its counterpart is of the
// feature-options reference. Padding is cosmetic - rendered markdown ignores it - so this is polish, not part of the semantic contract.
const MESSAGE_DIVIDER_WIDTH = 34;

// What joins the device labels inside one cell.
const LABEL_SEPARATOR = ", ";

// One rendered row: the cells its table prints in column order, the group it renders under, and the raw topic it sorts on. The raw topic is kept beside the rendered
// cells because sorting on the cell would sort on its markup, putting every parameterized topic in a block of its own.
interface TopicRow {

  readonly cells: readonly string[];
  readonly group?: string;
  readonly rawTopic: string;
}

// Neutralize the column separator in author-owned markdown. A bare "|" would open a phantom column, while backticks, links, and alert markup have to reach the
// document exactly as the plugin wrote them - so this is the only transformation a message text or a device label receives.
function escapeColumnSeparator(text: string): string {

  return text.replaceAll("|", "\\|");
}

// Render a raw topic as the document shows it. A plain tail sits in a backtick code span; a template becomes an HTML code span so each placeholder can be italicized
// in place, which markdown offers no way to do inside a backtick span. The substitution goes through the resolver, so the markup form and the wire form are produced
// by one statement of what a placeholder is.
function renderTopicCell(rawTopic: string): string {

  const placeholders = mqttTopicPlaceholders(rawTopic);

  if(placeholders.length === 0) {

    return "`" + rawTopic + "`";
  }

  return "<CODE>" + resolveMqttTopic(rawTopic, Object.fromEntries(placeholders.map((name) => [ name, "<I>" + name + "</I>" ]))) + "</CODE>";
}

// Validate an entry's device declaration against the catalog's column and render its cell. The column and the lists are one decision, so both directions are checked
// here: with a column every entry names at least one kind the vocabulary declares, and without one no entry names any. The labels are joined in the vocabulary's
// declared order rather than the entry's, so one declaration fixes how every cell in the column reads.
function renderDeviceCell({ column, entry, key }: { column: MqttTopicDeviceColumn | undefined; entry: MqttTopicEntry; key: string }): string {

  if(column === undefined) {

    if(entry.devices !== undefined) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " declares devices but the catalog declares no column.");
    }

    return "";
  }

  const devices = entry.devices;

  if((devices === undefined) || (devices.length === 0)) {

    throw new Error("renderMqttTopicsReference: the column \"" + column.heading + "\" needs a devices list on the entry " + key + ".");
  }

  for(const device of devices) {

    if(!(device in column.vocabulary)) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " names a device \"" + device + "\" the column's vocabulary does not declare.");
    }
  }

  return escapeColumnSeparator(Object.entries(column.vocabulary).filter(([name]) => devices.includes(name)).map(([ , label ]) => label).join(LABEL_SEPARATOR));
}

// Build one row from an entry's declaration. The message text and the device labels are author-owned markdown and receive only the separator escape; the topic cell
// is this module's own markup.
function buildRow({ deviceCell, group, message, rawTopic, withColumn }: {

  deviceCell: string;
  group?: string;
  message: string;
  rawTopic: string;
  withColumn: boolean;
}): TopicRow {

  const cells = withColumn ? [ renderTopicCell(rawTopic), deviceCell, escapeColumnSeparator(message) ] :
    [ renderTopicCell(rawTopic), escapeColumnSeparator(message) ];

  return { cells, group, rawTopic };
}

// Order two rows by their raw topic, ascending by code unit. Sorting on the raw topic rather than on declaration order is what puts a get child beside its set child
// and `light` ahead of `light/brightness`, which is how every shipped document in the family already reads.
function byRawTopic(left: TopicRow, right: TopicRow): number {

  if(left.rawTopic < right.rawTopic) {

    return -1;
  }

  return (left.rawTopic > right.rawTopic) ? 1 : 0;
}

// Render one section: a single table for an ungrouped catalog, or one table per group that has rows in this section, each under its own H4 heading. Nothing to list
// renders nothing, at either level - a section the catalog has no rows for is an empty fragment, and a group with no rows in this section is left out of it - so a
// plugin never gets a heading, a divider, or a header row standing over nothing.
function renderSection(rows: readonly TopicRow[], groups: readonly string[], headings: readonly string[]): string {

  if(rows.length === 0) {

    return "";
  }

  const lines: string[] = [];

  if(groups.length === 0) {

    lines.push(...renderMarkdownTable({ dividerWidth: MESSAGE_DIVIDER_WIDTH, headings, rows: rows.map((row) => row.cells) }));
    lines.push("");

    return lines.join("\n");
  }

  for(const group of groups) {

    const groupRows = rows.filter((row) => row.group === group);

    if(groupRows.length === 0) {

      continue;
    }

    lines.push("#### " + group);
    lines.push("");
    lines.push(...renderMarkdownTable({ dividerWidth: MESSAGE_DIVIDER_WIDTH, headings, rows: groupRows.map((row) => row.cells) }));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Render an MQTT topic catalog into the two markdown fragments a plugin embeds in its `docs/MQTT.md`: the published-topics tables and the subscribed-topics tables.
 *
 * One traversal validates the catalog and emits both sections' rows. The validation is the document's own, not the builder's: the compiled JavaScript the CLI loads
 * carries no types, so the checks a declaration's shape would otherwise make at compile time are made here instead, and a documentation mistake fails the docs
 * build rather than a plugin's startup. Every message names the offending entry by key.
 *
 * Rows are sorted by their raw topic, grouped when the catalog declares groups, and given a device column when the catalog declares one, with each entry's labels
 * joined in the order the vocabulary declares them. A section the catalog has no rows for is an empty string.
 *
 * @param catalog - The catalog to project, as {@link mqtt-topics!mqttTopicCatalog | mqttTopicCatalog} returned it.
 *
 * @returns The two fragments, one per marked region.
 *
 * @throws `Error` naming the offending entry when the catalog declares a column without a string heading or a vocabulary object, when a column is declared and an
 *         entry carries no devices list or names a kind the vocabulary does not declare, when no column is declared and an entry carries a devices list, or when
 *         some entries declare a group and others do not.
 *
 * @category Utilities
 */
export function renderMqttTopicsReference(catalog: MqttTopicCatalog): MqttTopicsReference {

  const column = catalog[MQTT_DEVICE_COLUMN];

  if(column !== undefined) {

    // The CLI loads a plugin's COMPILED catalog, and compiled JavaScript carries no types, so the column arrives as whatever that module exported. These two checks
    // are the ones the declaration's own type would have made at authoring time, made here instead - which is why the column is read through a view that admits the
    // shapes the type says cannot occur.
    const declared: { heading?: unknown; vocabulary?: unknown } = column;

    if(typeof declared.heading !== "string") {

      throw new Error("renderMqttTopicsReference: the catalog's device column declares no heading text.");
    }

    if((typeof declared.vocabulary !== "object") || (declared.vocabulary === null)) {

      throw new Error("renderMqttTopicsReference: the catalog's device column \"" + column.heading + "\" declares no vocabulary object.");
    }
  }

  const published: TopicRow[] = [];
  const subscribed: TopicRow[] = [];
  const groups: string[] = [];

  // The first entry sets the catalog's grouping expectation, and the first entry that departs from it is named against that one - a rule with no tie to break.
  let expectation: { grouped: boolean; key: string } | undefined;

  for(const [ key, entry ] of Object.entries(catalog)) {

    const deviceCell = renderDeviceCell({ column, entry, key });
    const grouped = entry.group !== undefined;

    expectation ??= { grouped, key };

    if(expectation.grouped !== grouped) {

      throw new Error("renderMqttTopicsReference: the entry " + key + " declares " + (grouped ? "a group while the entry " : "no group while the entry ") +
        expectation.key + (grouped ? " declares none." : " declares one."));
    }

    if((entry.group !== undefined) && !groups.includes(entry.group)) {

      groups.push(entry.group);
    }

    const withColumn = column !== undefined;

    if(entry.publish !== undefined) {

      published.push(buildRow({ deviceCell, group: entry.group, message: entry.publish, rawTopic: entry.topic, withColumn }));
    }

    if(entry.get !== undefined) {

      subscribed.push(buildRow({ deviceCell, group: entry.group, message: entry.get, rawTopic: mqttGetTopic(entry.topic), withColumn }));
    }

    if(entry.set !== undefined) {

      subscribed.push(buildRow({ deviceCell, group: entry.group, message: entry.set, rawTopic: mqttSetTopic(entry.topic), withColumn }));
    }
  }

  const leadingHeadings = (column === undefined) ? ["Topic"] : [ "Topic", column.heading ];

  return {

    published: renderSection(published.toSorted(byRawTopic), groups, [ ...leadingHeadings, "Message Published" ]),
    subscribed: renderSection(subscribed.toSorted(byRawTopic), groups, [ ...leadingHeadings, "Message Expected" ])
  };
}
