/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * webui-loader.ts: The marker-gated stamp for a plugin's webUI script loader.
 */

/**
 * The webUI script-loader stamp. A plugin's `index.html` hand-copies an importmap/cache-bust `<script type="module">` block whose runtime job is to read the
 * homebridge-plugin-utils manifest, inject an importmap mapping the bare package specifier to the hashed-versioned subdir the `prepare-ui` CLI mirrors into place, and
 * dynamically import the plugin's entry module. That block is identical across the family, so this module renders it from one template: the plugin declares its entry
 * and cache-bust list in a config comment, and `prepare-ui` stamps the rendered block into a marker-fenced region on every build.
 *
 * Three pieces: the marked-region marker constants (following the family's uniform template - see `docChrome.ts`), {@link parseWebUiLoaderConfig} which reads and
 * validates the plugin's config comment, and {@link renderWebUiLoaderScript} which renders the loader block from that config plus the destination and package facts
 * the CLI supplies. The CLI's `prepareUi` owns the read/splice/atomic-write around them.
 *
 * @module
 */

// The config-comment prefix and terminator. The plugin declares its loader config in a single HTML comment - `<!-- WEBUI LOADER CONFIG {...} -->` - placed OUTSIDE the
// stamped marker pair, so it survives every stamp. The prefix is distinct from the BEGIN marker below (`... LOADER CONFIG ` versus `... LOADER:BEGIN`), so a search for
// one never matches the other.
const CONFIG_PREFIX = "<!-- WEBUI LOADER CONFIG ";
const COMMENT_TERMINATOR = "-->";

/**
 * The opening marker of the auto-generated webUI script-loader region. Follows the family's uniform marked-region template (see `docChrome.ts`); the text doubles as
 * an in-document warning not to edit the region by hand.
 *
 * @category WebUI Loader
 */
export const WEBUI_LOADER_BEGIN = "<!-- WEBUI LOADER:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated webUI script-loader region. See {@link WEBUI_LOADER_BEGIN}.
 *
 * @category WebUI Loader
 */
export const WEBUI_LOADER_END = "<!-- WEBUI LOADER:END -->";

/**
 * The validated shape of a plugin's webUI loader config: the entry module the loader dynamically imports, and the list of hand-authored modules (the entry aside) that
 * sit outside the package's hashed versioning and therefore each need a cache-bust.
 *
 * @category WebUI Loader
 */
export interface WebUiLoaderConfig {

  readonly bust: readonly string[];
  readonly entry: string;
}

/**
 * Read and validate the plugin's webUI loader config comment from an `index.html`. The comment is the plugin's sole declaration - its entry module and its cache-bust
 * list - and everything else about the rendered loader is a family constant or a fact the CLI supplies, so this is where a mistake in that declaration surfaces with a
 * message naming the file and the defect.
 *
 * Rejects, each with a framed error naming `htmlPath`: an absent config comment, a duplicated one (the region it drives would be ambiguous), an unterminated one,
 * invalid JSON, a mis-shaped object (a missing/non-string `entry`, or a `bust` that is not a string array), and a config comment sitting INSIDE the marked region (the
 * first stamp would erase it, so it must live outside the marker pair).
 *
 * @param html     - The full `index.html` text.
 * @param htmlPath - The path the html was read from, named in every diagnostic.
 *
 * @returns The validated {@link WebUiLoaderConfig}.
 *
 * @throws `Error` naming `htmlPath` and the defect for an absent, duplicated, unterminated, invalid-JSON, mis-shaped, or inside-the-region config comment.
 *
 * @category WebUI Loader
 */
export function parseWebUiLoaderConfig(html: string, htmlPath: string): WebUiLoaderConfig {

  const configIndex = html.indexOf(CONFIG_PREFIX);

  if(configIndex === -1) {

    throw new Error("webui-loader: no `<!-- WEBUI LOADER CONFIG ... -->` comment found in " + htmlPath + ".");
  }

  // A duplicated config comment leaves the loader config ambiguous - which entry/bust set drives the stamp is undefined - so reject it the same way the splice rejects
  // duplicated markers.
  if(html.includes(CONFIG_PREFIX, configIndex + CONFIG_PREFIX.length)) {

    throw new Error("webui-loader: multiple `WEBUI LOADER CONFIG` comments found in " + htmlPath + "; the loader config is ambiguous.");
  }

  // A config comment inside the marked region would be erased by the first stamp, so it must sit outside the marker pair. We position-check it against the marker
  // indices; when the markers are absent the check is inert (the stamp step gates on the BEGIN marker's presence before this runs).
  const beginIndex = html.indexOf(WEBUI_LOADER_BEGIN);
  const endIndex = html.indexOf(WEBUI_LOADER_END);

  if((beginIndex !== -1) && (endIndex !== -1) && (configIndex > beginIndex) && (configIndex < endIndex)) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` comment sits inside the marked region in " + htmlPath + "; move it outside the marker pair.");
  }

  const jsonStart = configIndex + CONFIG_PREFIX.length;
  const commentEnd = html.indexOf(COMMENT_TERMINATOR, jsonStart);

  if(commentEnd === -1) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` comment in " + htmlPath + " is not terminated.");
  }

  const rawJson = html.slice(jsonStart, commentEnd).trim();
  let parsed: unknown;

  try {

    parsed = JSON.parse(rawJson);
  } catch(error) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` comment in " + htmlPath + " is not valid JSON: " + (error instanceof Error ? error.message : String(error)) +
      ".");
  }

  if((typeof parsed !== "object") || (parsed === null)) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` in " + htmlPath + " must be a JSON object with an `entry` string and an optional `bust` string array.");
  }

  const config = parsed as { bust?: unknown; entry?: unknown };

  if(typeof config.entry !== "string") {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` in " + htmlPath + " must carry an `entry` string.");
  }

  if((config.bust !== undefined) && (!Array.isArray(config.bust) || config.bust.some((item) => typeof item !== "string"))) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` `bust` field in " + htmlPath + " must be an array of strings.");
  }

  return { bust: (config.bust as string[] | undefined) ?? [], entry: config.entry };
}

/**
 * Render the webUI script-loader block from the plugin's config plus the destination and package facts the CLI supplies. The rendered block reproduces the proven
 * runtime semantics of the hand-authored loader: a single `Date.now()` cache-bust stamp shared across the page load, a `bust()` helper that resolves a path against
 * `import.meta.url` and appends the stamp, a `cache: "no-store"` fetch of the manifest, an importmap, and a dynamic import of the entry.
 *
 * Every importmap module entry keeps the BARE module path as its KEY with the busted URL as its VALUE - the entry module ITSELF plus every declared `bust` entry, so
 * the most important module (the entry) is never served stale. The trailing-slash `<packageName>/` prefix entry maps the bare package specifier to the hashed-versioned
 * subdir, and transitive imports inherit it through relative-URL resolution.
 *
 * `libPath` is the destination-relative segment the CLI derives from its `dest` basename (`"./lib/"` for the family convention), so the manifest fetch path and the
 * prefix URL are path-correct for any destination rather than a hardcoded `./lib/` that is only coincidentally right for one plugin.
 *
 * @param args
 * @param args.bust        - The hand-authored modules (the entry aside) that each need a cache-bust.
 * @param args.entry       - The entry module the loader dynamically imports; it is cache-busted alongside the `bust` list.
 * @param args.libPath     - The destination-relative segment (e.g. `"./lib/"`) the manifest fetch and the importmap prefix resolve against.
 * @param args.packageName - The mirrored package's name; the importmap prefix maps `<packageName>/` to the hashed-versioned subdir.
 *
 * @returns The `<script type="module"> ... </script>` block to splice between the marker pair.
 *
 * @category WebUI Loader
 */
export function renderWebUiLoaderScript({ bust, entry, libPath, packageName }: { bust: readonly string[]; entry: string; libPath: string; packageName: string }): string {

  // The busted modules: the entry itself plus every declared bust entry, de-duplicated and sorted so the importmap is stable across runs. The entry is busted too -
  // it sits outside the package's hashed versioning, so an unbusted entry would let the browser serve a stale copy of the most important module.
  const bustedModules = [...new Set([ entry, ...bust ])].toSorted();
  const importLines = bustedModules.map((module) => "      \"" + module + "\": bust(\"" + module + "\"),");
  const prefixLine = "      \"" + packageName + "/\": new URL(\"" + libPath + "\" + manifest.subdir + \"/\", import.meta.url).href";

  // Assemble the block line by line and join with LF. String concatenation, not template literals, matches the house style and keeps the busted entries and dynamic
  // segments explicit at each interpolation point.
  return [

    "<script type=\"module\">",
    "  /* Plugin webUI script loader, generated by homebridge-plugin-utils from the loader-config comment above - do not edit this region by hand. It reads the",
    "   * homebridge-plugin-utils manifest at load time and injects an importmap mapping the bare \"" + packageName + "/\" specifier to the hashed-versioned subdir the",
    "   * prepare-ui CLI mirrors into place; the trailing-slash prefix carries transitive imports through relative-URL resolution, and each hand-authored module carries",
    "   * a Date.now() cache-bust so a single page load stays coherent across them.",
    "   */",
    "",
    "  const cb = Date.now();",
    "  const bust = (path) => new URL(path, import.meta.url).href + \"?cb=\" + cb;",
    "",
    "  const manifest = await fetch(\"" + libPath + "manifest.json\", { cache: \"no-store\" }).then((response) => response.json());",
    "",
    "  const importMap = {",
    "",
    "    imports: {",
    "",
    ...importLines,
    prefixLine,
    "    }",
    "  };",
    "",
    "  const mapScript = document.createElement(\"script\");",
    "",
    "  mapScript.type = \"importmap\";",
    "  mapScript.textContent = JSON.stringify(importMap);",
    "  document.head.appendChild(mapScript);",
    "",
    "  await import(\"" + entry + "\");",
    "</script>"
  ].join("\n");
}
