/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * webui-loader.ts: The marker-gated stamp for a plugin's webUI boot region.
 */

/**
 * The webUI boot-region stamp. A plugin's `index.html` carries a marker-fenced region that homebridge-plugin-utils generates and every build re-stamps. The region
 * reports its own boot failures on the page, injects an importmap mapping the bare package specifier to the hashed-versioned subdir the `prepare-ui` CLI mirrors into
 * place, and dynamically imports the plugin's entry module. It is identical across the family, so this module renders it from one template: the plugin declares its
 * entry and cache-bust list in a config comment, and `prepare-ui` stamps the rendered region into the marker-fenced block on every build.
 *
 * The region carries three pieces in boot order. A hidden status panel a screenshot turns into a complete support report. A boot monitor - a classic inline script, so
 * it runs during HTML parse ahead of any deferred module evaluation - that owns the on-page failure surface: it reveals the panel with a plain-language message
 * classified by the boot stage that failed, arms a ten-second watchdog for a boot that hangs, and stands down when the app signals it rendered. And the loader - the
 * importmap/cache-bust module script - stage-instrumented so a fetch, importmap, or entry-import failure routes to the monitor with the stage that failed. The
 * classic-versus-module split is for execution ordering alone, not old-engine compatibility: the classic script runs during parse while the module script is deferred.
 *
 * Three exported pieces: the marked-region marker constants (following the family's uniform template - see `docChrome.ts`), {@link parseWebUiLoaderConfig} which reads
 * and validates the plugin's config comment, and {@link renderWebUiBootRegion} which renders the region from that config plus the destination and package facts the CLI
 * supplies. The CLI's `prepareUi` owns the read/splice/atomic-write around them.
 *
 * @module
 */

// The config-comment prefix and terminator. The plugin declares its loader config in a single HTML comment - `<!-- WEBUI LOADER CONFIG {...} -->` - placed OUTSIDE the
// stamped marker pair, so it survives every stamp. The prefix is distinct from the BEGIN marker below (`... LOADER CONFIG ` versus `... LOADER:BEGIN`), so a search for
// one never matches the other.
const CONFIG_PREFIX = "<!-- WEBUI LOADER CONFIG ";
const COMMENT_TERMINATOR = "-->";

/**
 * The opening marker of the auto-generated webUI boot region. Follows the family's uniform marked-region template (see `docChrome.ts`); the text doubles as an
 * in-document warning not to edit the region by hand.
 *
 * @category WebUI Loader
 */
export const WEBUI_LOADER_BEGIN = "<!-- WEBUI LOADER:BEGIN - Auto-generated by homebridge-plugin-utils. Do not edit this region by hand. -->";

/**
 * The closing marker of the auto-generated webUI boot region. See {@link WEBUI_LOADER_BEGIN}.
 *
 * @category WebUI Loader
 */
export const WEBUI_LOADER_END = "<!-- WEBUI LOADER:END -->";

/**
 * The validated shape of a plugin's webUI loader config: the entry module the loader dynamically imports, and the list of hand-authored modules (the entry aside) that
 * sit outside the package's hashed versioning and therefore each need a cache-bust.
 *
 * @category WebUI Loader
 */
export interface WebUiLoaderConfig {

  readonly bust: readonly string[];
  readonly entry: string;
}

/**
 * Read and validate the plugin's webUI loader config comment from an `index.html`. The comment is the plugin's sole declaration - its entry module and its cache-bust
 * list - and everything else about the rendered region is a family constant or a fact the CLI supplies, so this is where a mistake in that declaration surfaces with a
 * message naming the file and the defect.
 *
 * Rejects, each with a framed error naming `htmlPath`: an absent config comment, a duplicated one (the region it drives would be ambiguous), an unterminated one,
 * invalid JSON, a mis-shaped object (a missing/non-string `entry`, or a `bust` that is not a string array), and a config comment sitting INSIDE the marked region (the
 * first stamp would erase it, so it must live outside the marker pair).
 *
 * @param html     - The full `index.html` text.
 * @param htmlPath - The path the html was read from, named in every diagnostic.
 *
 * @returns The validated {@link WebUiLoaderConfig}.
 *
 * @throws `Error` naming `htmlPath` and the defect for an absent, duplicated, unterminated, invalid-JSON, mis-shaped, or inside-the-region config comment.
 *
 * @category WebUI Loader
 */
export function parseWebUiLoaderConfig(html: string, htmlPath: string): WebUiLoaderConfig {

  const configIndex = html.indexOf(CONFIG_PREFIX);

  if(configIndex === -1) {

    throw new Error("webui-loader: no `<!-- WEBUI LOADER CONFIG ... -->` comment found in " + htmlPath + ".");
  }

  // A duplicated config comment leaves the loader config ambiguous - which entry/bust set drives the stamp is undefined - so reject it the same way the splice rejects
  // duplicated markers.
  if(html.includes(CONFIG_PREFIX, configIndex + CONFIG_PREFIX.length)) {

    throw new Error("webui-loader: multiple `WEBUI LOADER CONFIG` comments found in " + htmlPath + "; the loader config is ambiguous.");
  }

  // A config comment inside the marked region would be erased by the first stamp, so it must sit outside the marker pair. We position-check it against the marker
  // indices; when the markers are absent the check is inert (the stamp step gates on the BEGIN marker's presence before this runs).
  const beginIndex = html.indexOf(WEBUI_LOADER_BEGIN);
  const endIndex = html.indexOf(WEBUI_LOADER_END);

  if((beginIndex !== -1) && (endIndex !== -1) && (configIndex > beginIndex) && (configIndex < endIndex)) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` comment sits inside the marked region in " + htmlPath + "; move it outside the marker pair.");
  }

  const jsonStart = configIndex + CONFIG_PREFIX.length;
  const commentEnd = html.indexOf(COMMENT_TERMINATOR, jsonStart);

  if(commentEnd === -1) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` comment in " + htmlPath + " is not terminated.");
  }

  const rawJson = html.slice(jsonStart, commentEnd).trim();
  let parsed: unknown;

  try {

    parsed = JSON.parse(rawJson);
  } catch(error) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` comment in " + htmlPath + " is not valid JSON: " + (error instanceof Error ? error.message : String(error)) +
      ".");
  }

  if((typeof parsed !== "object") || (parsed === null)) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` in " + htmlPath + " must be a JSON object with an `entry` string and an optional `bust` string array.");
  }

  const config = parsed as { bust?: unknown; entry?: unknown };

  if(typeof config.entry !== "string") {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` in " + htmlPath + " must carry an `entry` string.");
  }

  if((config.bust !== undefined) && (!Array.isArray(config.bust) || config.bust.some((item) => typeof item !== "string"))) {

    throw new Error("webui-loader: the `WEBUI LOADER CONFIG` `bust` field in " + htmlPath + " must be an array of strings.");
  }

  return { bust: (config.bust as string[] | undefined) ?? [], entry: config.entry };
}

// The plain-language boot-failure copy the status panel shows, approved in design and expanded to complete sentences. The browser, delivery, and generic strings are
// the three classified message buckets the boot monitor reveals by stage; the slow notice is the watchdog's still-working signal; the headline sits above them all.
// The copy lives here as panel text content, not as monitor script constants, so it renders exactly and contiguously on the page and stays clear of this file's
// line-width wrap - HTML text content carries no such limit, and a long single-sentence string cannot be broken without splitting it away from a support grep.
const BOOT_HEADLINE = "The settings interface couldn't load.";
const BOOT_MESSAGE_BROWSER = "Your browser doesn't support features this interface requires. Please use a current version of Safari or Chrome.";
const BOOT_MESSAGE_DELIVERY = "The interface files couldn't be retrieved from the Homebridge server. Reload the page to try again. " +
  "If this keeps happening, log out of the Homebridge interface and log back in.";
const BOOT_MESSAGE_GENERIC = "An unexpected error occurred while starting the interface.";
const BOOT_SLOW_NOTICE = "This is taking longer than expected. If nothing appears shortly, reload the page.";

// The status panel markup: a hidden, centered block that a screenshot turns into a complete support report. It starts fully hidden and is revealed by the boot monitor
// alone. The three bucket messages are pre-rendered and each hidden, so the monitor reveals the classified one without ever assigning message text at runtime; only the
// untrusted technical details are filled in through `textContent` at reveal time. The `<details open>` disclosure shows those details the moment the panel appears - a
// screenshot is then a complete report - while staying collapsible after reading. The sibling slow notice carries the watchdog's still-working line, hidden until armed.
const BOOT_STATUS_PANEL: readonly string[] = [

  "<div id=\"pageBootError\" class=\"mt-4 text-center\" style=\"display: none;\">",
  "  <h5>" + BOOT_HEADLINE + "</h5>",
  "  <div id=\"bootErrorMessage\">",
  "    <p data-boot-bucket=\"browser\" style=\"display: none;\">" + BOOT_MESSAGE_BROWSER + "</p>",
  "    <p data-boot-bucket=\"delivery\" style=\"display: none;\">" + BOOT_MESSAGE_DELIVERY + "</p>",
  "    <p data-boot-bucket=\"generic\" style=\"display: none;\">" + BOOT_MESSAGE_GENERIC + "</p>",
  "  </div>",
  "  <details open>",
  "    <summary>Technical details</summary>",
  "    <div id=\"bootErrorDetails\"></div>",
  "  </details>",
  "</div>",
  "<div id=\"bootSlowNotice\" class=\"mt-4 text-center\" style=\"display: none;\">" + BOOT_SLOW_NOTICE + "</div>"
];

// The boot monitor: a classic inline script that runs during HTML parse, ahead of the deferred module loader, so it can catch a failure anywhere along the boot path
// and report it on the page. Its whole body is an IIFE guarded against a second execution in the same window, exposing a frozen `window.webUiBoot` with `fail` and
// `ready`, window `error`/`unhandledrejection` listeners, and a ten-second watchdog. First failure wins; `ready()` from the app supersedes it. The block is static -
// no plugin fact reaches it - so it is a constant the renderer splices verbatim between the panel and the loader.
const BOOT_MONITOR: readonly string[] = [

  "<script>",
  "  /* Boot monitor for the plugin webUI, generated by homebridge-plugin-utils - do not edit this region by hand. This is a classic inline script, so it runs during",
  "   * HTML parse ahead of the deferred module loader below and can report a failure anywhere along the boot path. It reveals the hidden status panel with the message",
  "   * bucket the failing stage names, arms a ten-second watchdog for a boot that hangs, and stands down when webUi.show() signals the app rendered or displayed its",
  "   * own error. The classic-versus-module split is for execution ordering alone: a classic inline script runs during parse while a module script is deferred.",
  "   */",
  "  (function() {",
  "",
  "    // A second execution in the same window - a reused iframe across repeated settings-panel opens - returns immediately, so the first run's listeners and watchdog",
  "    // are never duplicated into an orphaned registration that could resurrect the panel over a working app.",
  "    if(window.webUiBoot) {",
  "",
  "      return;",
  "    }",
  "",
  "    const watchdogMs = 10000;",
  "",
  "    // The stage-to-bucket map. The browser stage stands alone, the manifest and import delivery stages share the delivery bucket, and every other stage - an",
  "    // uncaught window error or unhandled rejection included - falls through the nullish default to the generic bucket.",
  "    const buckets = { browser: \"browser\", import: \"delivery\", manifest: \"delivery\" };",
  "",
  "    let settled = false;",
  "    let watchdog;",
  "",
  "    // Set an element's display by id, tolerating an absent node so a stamped region missing a panel element never throws from the monitor.",
  "    const setDisplay = (id, value) => {",
  "",
  "      const element = document.getElementById(id);",
  "",
  "      if(element) {",
  "",
  "        element.style.display = value;",
  "      }",
  "    };",
  "",
  "    // Stop watching: clear the watchdog and remove both window listeners. Called from the first failure and from ready(), so nothing is left open once the boot has",
  "    // resolved one way or the other.",
  "    const stop = () => {",
  "",
  "      clearTimeout(watchdog);",
  "      window.removeEventListener(\"error\", onError);",
  "      window.removeEventListener(\"unhandledrejection\", onRejection);",
  "    };",
  "",
  "    // The first failure wins. Reveal the panel with the classified bucket message and the technical details, retract any slow notice the watchdog raised, stop",
  "    // watching, and drop the host spinner so it cannot mask the panel. A later failure, and any failure after ready(), is ignored. The handlers never call",
  "    // preventDefault(), so the browser console keeps every error and the panel only complements it.",
  "    const fail = (stage, error) => {",
  "",
  "      if(settled) {",
  "",
  "        return;",
  "      }",
  "",
  "      settled = true;",
  "",
  "      stop();",
  "",
  "      // Reveal the one pre-rendered message the failing stage's bucket names; the bucket keys are internal constants, never user input, so the selector is safe.",
  "      const chosen = document.querySelector(\"#bootErrorMessage [data-boot-bucket='\" + (buckets[stage] ?? \"generic\") + \"']\");",
  "",
  "      if(chosen) {",
  "",
  "        chosen.style.display = \"block\";",
  "      }",
  "",
  "      const details = document.getElementById(\"bootErrorDetails\");",
  "",
  "      if(details) {",
  "",
  "        // The error text is untrusted, so each detail line is assigned as plain text through textContent and is never parsed as markup.",
  "        const lines = [ \"Stage: \" + stage, \"Error: \" + ((error instanceof Error) ? error.message : String(error)), \"Browser: \" + navigator.userAgent ];",
  "",
  "        details.textContent = \"\";",
  "",
  "        for(const line of lines) {",
  "",
  "          const row = document.createElement(\"div\");",
  "",
  "          row.textContent = line;",
  "          details.appendChild(row);",
  "        }",
  "      }",
  "",
  "      setDisplay(\"bootSlowNotice\", \"none\");",
  "      setDisplay(\"pageBootError\", \"block\");",
  "      globalThis.homebridge?.hideSpinner?.();",
  "    };",
  "",
  "    // The app is authoritative and supersedes anything the monitor showed. webUi.show() calls this from its finally once it has rendered or displayed its own toast,",
  "    // so an earlier boot-phase error was evidently non-fatal - browser-extension noise on window.onerror is real. Stop watching, retract both the slow notice and",
  "    // the panel, and mark settled so a later fail() is a no-op.",
  "    const ready = () => {",
  "",
  "      settled = true;",
  "",
  "      stop();",
  "",
  "      setDisplay(\"bootSlowNotice\", \"none\");",
  "      setDisplay(\"pageBootError\", \"none\");",
  "    };",
  "",
  "    const onError = (event) => fail(\"uncaught error\", event.error ?? event.message);",
  "    const onRejection = (event) => fail(\"unhandled rejection\", event.reason);",
  "",
  "    window.webUiBoot = Object.freeze({ fail, ready });",
  "",
  "    window.addEventListener(\"error\", onError);",
  "    window.addEventListener(\"unhandledrejection\", onRejection);",
  "",
  "    // Arm the watchdog. Nothing reported by the deadline means the boot has stalled, so show the slow notice in the spinner's place and drop the spinner; a boot",
  "    // that finishes later retracts the notice through ready(). The watchdog tears nothing down - boot may still succeed.",
  "    watchdog = setTimeout(() => {",
  "",
  "      setDisplay(\"bootSlowNotice\", \"block\");",
  "      globalThis.homebridge?.hideSpinner?.();",
  "    }, watchdogMs);",
  "  })();",
  "</script>"
];

/**
 * Render the webUI boot region from the plugin's config plus the destination and package facts the CLI supplies. The region carries, in boot order, a hidden status
 * panel, a classic-script boot monitor, and the importmap/cache-bust module loader. The loader reproduces the proven runtime semantics of the hand-authored block: a
 * single `Date.now()` cache-bust stamp shared across the page load, a `bust()` helper that resolves a path against `import.meta.url` and appends the stamp, a
 * `cache: "no-store"` fetch of the manifest, an importmap, and a dynamic import of the entry, all wrapped in a stage-instrumented `try`/`catch` that routes a boot
 * failure to the monitor with the stage that failed, without adding any await or work to the happy path.
 *
 * The catch classifies by stage. A manifest-stage failure reports directly, with no capability probe: the importmap is not injected yet, so probing resolution there
 * would misroute every ordinary delivery failure into the browser bucket. At the import stage the map is injected, so an engine without `import.meta.resolve` predates
 * the loader's floor, and a probe of the injected prefix that throws proves the map never applied - either is the browser bucket - while a resolving probe leaves the
 * failure in the delivery bucket. The probe proves the map applied, not that the delivered module content is sound: a top-level throw inside a delivered module is
 * indistinguishable from a fetch failure here and knowingly folds into the delivery bucket, where the panel's raw error line disambiguates it for support.
 *
 * Every importmap module entry keeps the BARE module path as its KEY with the busted URL as its VALUE - the entry module ITSELF plus every declared `bust` entry, so
 * the most important module (the entry) is never served stale. The trailing-slash `<packageName>/` prefix entry maps the bare package specifier to the hashed-versioned
 * subdir, and transitive imports inherit it through relative-URL resolution.
 *
 * `libPath` is the destination-relative segment the CLI derives from its `dest` basename (`"./lib/"` for the family convention), so the manifest fetch path and the
 * prefix URL are path-correct for any destination rather than a hardcoded `./lib/` that is only coincidentally right for one plugin.
 *
 * @param args
 * @param args.bust        - The hand-authored modules (the entry aside) that each need a cache-bust.
 * @param args.entry       - The entry module the loader dynamically imports; it is cache-busted alongside the `bust` list.
 * @param args.libPath     - The destination-relative segment (e.g. `"./lib/"`) the manifest fetch and the importmap prefix resolve against.
 * @param args.packageName - The mirrored package's name; the importmap prefix maps `<packageName>/` to the hashed-versioned subdir, and the import-stage probe resolves
 *                           `<packageName>/webUi.mjs` against it.
 *
 * @returns The marked-region content - the status panel, the boot monitor, and the `<script type="module">` loader - to splice between the marker pair.
 *
 * @category WebUI Loader
 */
export function renderWebUiBootRegion({ bust, entry, libPath, packageName }: { bust: readonly string[]; entry: string; libPath: string; packageName: string }): string {

  // The busted modules: the entry itself plus every declared bust entry, de-duplicated and sorted so the importmap is stable across runs. The entry is busted too -
  // it sits outside the package's hashed versioning, so an unbusted entry would let the browser serve a stale copy of the most important module.
  const bustedModules = [...new Set([ entry, ...bust ])].toSorted();
  const importLines = bustedModules.map((module) => "        \"" + module + "\": bust(\"" + module + "\"),");
  const prefixLine = "        \"" + packageName + "/\": new URL(\"" + libPath + "\" + manifest.subdir + \"/\", import.meta.url).href";

  // The stage-instrumented module loader. Its runtime happy path is identical to the hand-authored block; the `try`/`catch` and the `let stage` add only the failure
  // route to the monitor. `stage` starts `"manifest"` and flips to `"import"` immediately before the entry import, so the importmap build and injection between them
  // still report under `"manifest"`.
  const loaderLines = [

    "<script type=\"module\">",
    "  /* Plugin webUI loader, generated by homebridge-plugin-utils from the loader-config comment above - do not edit this region by hand. It reads the",
    "   * homebridge-plugin-utils manifest at load time and injects an importmap mapping the bare \"" + packageName + "/\" specifier to the hashed-versioned subdir the",
    "   * prepare-ui CLI mirrors into place; the trailing-slash prefix carries transitive imports through relative-URL resolution, and each hand-authored module carries",
    "   * a Date.now() cache-bust so a single page load stays coherent across them. The body is stage-instrumented: a fetch, importmap, or entry-import failure is",
    "   * reported to the boot monitor above with the stage that failed, which reveals the on-page status panel. The import-stage probe proves the injected importmap",
    "   * applied - a browser that ignored it lands in the browser bucket - but it cannot tell a delivery failure from a top-level throw inside a delivered module, so",
    "   * that case knowingly folds into the delivery bucket and the panel's raw error line is what disambiguates it for support.",
    "   */",
    "",
    "  const cb = Date.now();",
    "  const bust = (path) => new URL(path, import.meta.url).href + \"?cb=\" + cb;",
    "",
    "  let stage = \"manifest\";",
    "",
    "  try {",
    "",
    "    const response = await fetch(\"" + libPath + "manifest.json\", { cache: \"no-store\" });",
    "",
    "    if(!response.ok) {",
    "",
    "      throw new Error(\"The manifest request failed with HTTP status \" + response.status + \".\");",
    "    }",
    "",
    "    const manifest = await response.json();",
    "",
    "    const importMap = {",
    "",
    "      imports: {",
    "",
    ...importLines,
    prefixLine,
    "      }",
    "    };",
    "",
    "    const mapScript = document.createElement(\"script\");",
    "",
    "    mapScript.type = \"importmap\";",
    "    mapScript.textContent = JSON.stringify(importMap);",
    "    document.head.appendChild(mapScript);",
    "",
    "    stage = \"import\";",
    "",
    "    await import(\"" + entry + "\");",
    "  } catch(error) {",
    "",
    "    // The monitor owns the on-page display, so after classifying we report and swallow: rethrowing would only add a duplicate uncaught error to the console the",
    "    // original failure already produced.",
    "    if(stage === \"import\") {",
    "",
    "      if(typeof import.meta.resolve !== \"function\") {",
    "",
    "        window.webUiBoot.fail(\"browser\", error);",
    "      } else {",
    "",
    "        try {",
    "",
    "          import.meta.resolve(\"" + packageName + "/webUi.mjs\");",
    "          window.webUiBoot.fail(\"import\", error);",
    "        } catch {",
    "",
    "          window.webUiBoot.fail(\"browser\", error);",
    "        }",
    "      }",
    "    } else {",
    "",
    "      window.webUiBoot.fail(\"manifest\", error);",
    "    }",
    "  }",
    "</script>"
  ];

  // Assemble the region: the status panel, then the boot monitor, then the loader, separated by a blank line and joined with LF. The panel and monitor are static
  // constants; only the loader carries the plugin's busted entries and dynamic segments, kept explicit at each interpolation point through string concatenation rather
  // than template literals, matching the house style.
  return [ ...BOOT_STATUS_PANEL, "", ...BOOT_MONITOR, "", ...loaderLines ].join("\n");
}
