name: "Close Stale Issues"

on:
  issues:
    types: [reopened]
  schedule:
    - cron: "0 * * * *"

jobs:
  stale:
    uses: hjdhjd/github-workflows/.github/workflows/issue-stale.yml@main
    secrets: inherit
